steamcmd:
  path: "C:\\gameservers\\SteamCMD"
  app_id: 2430930
  username: "anonymous"

server:
  name: "[US East] Brohana 4xH/XP,8xT,16xB"
  ip_address: "192.168.1.42"
  install_path: "C:\\gameservers\\ark_survival_ascended"
  port: 7777
  query_port: 27015
  players: 26
  password: ""
  map: "TheIsland_WP"

rcon:
  path: "C:\\gameservers\\rcon-0.10.3-win64"
  port: 32330

restart:
  scheduled:
    interval: 24 # hours
    blackout_times: [07:00, 02:00] # range of times to NOT perform a scheduled reset from beginning to end
  update_check:
    interval: 1 # hours
  warnings: [10, 5, 1] # list of minutes to warn user before restart for scheduled restart or update check

announcement:
  interval: 2  # hours
  message: "Thanks for playing on Brohana. Server is still WIP and adjustments/mods may be made here and there. Discord (also WIP): https://discord.gg/GzbSc9UJ"

stale:
  interval: 0.5 # interval to check for a stale server in hours
  threshold: 2 # once a server is stale for this many hours, it will be restarted

mods:
  - 928988