name: ark
dependencies:
  - python=3.11.3
  - pip
  - pip:
    - pyyaml
    - requests
    - "steam[client]"
    - pytest
    - pytest-env
    - pytest-pythonpath
    - pytest-mock
    - python-dotenv
    - colorlog
    - tzlocal
    - cryptography
    - git+https://github.com/israel-dryer/ttkbootstrap.git#egg=ttkbootstrap