steamcmd:
  path: "C:\\gameservers\\SteamCMD"
  app_id: 2430930

server:
  name: "[US East] Brohana 4xH/XP,8xT,16xB"
  ip_address: "192.168.1.42"
  install_path: "C:\\gameservers\\ark_survival_ascended"
  port: 7777
  query_port: 27015
  rcon_port: 32330
  players: 26
  password: ""
  map: "TheIsland_WP"
  admin_password: "hello"

mods:
  - 928988

discord:
  webhook: "https://discord.com/api/webhooks/1169356449873412116/7NaksFrGxSfnxEbk2hAL7hqYMdKIxbskqJ6D1gr-OKdxKW4Gegb4KP70O25cDQzkaaSW"

tasks:
  restart:
    description: "Routine server restart"
    interval: 24 # hours
    blackout_times: [07:00, 02:00] # range of times to NOT perform a scheduled reset from beginning to end in 24hr time
    warnings: [10, 5, 1] # list of minutes to warn user before restart for scheduled restart or update check
  update:
    description: "Routine server update check"
    interval: 1
  destroy_wild_dinos:
    description: "Routine wild dino wipe"
    interval: 72
    blackout_times: [07:00, 02:00]
    warnings: [60, 30, 10, 1]
  announcement:
    interval: 1
    description: "Thanks for playing on Brohana. Server is still WIP and adjustments/mods may be made here and there. Discord (also WIP): https://discord.gg/GzbSc9UJ"
  stale:
    interval: 0.5 # interval to check for a stale server in hours
    threshold: 5 # once a server is stale for this many hours, it will be restarted
