# The Steam application ID for the ARK server
steam_app_id: 2430930

# Server configuration section
server:
  name: "MyArkServer" # The name of your ARK server
  ip_address: "192.168.1.42" # The internal IP address where your ARK server is hosted
  install_path: "C:\\gameservers\\ark_survival_ascended" # The file path where your ARK server files are installed
  port: 7777 # The main port for your ARK server
  query_port: 27015
  rcon_port: 32330
  max_players: 26 # The maximum number of players that can join the server
  password: "password" # Server password for private access (if needed)
  map: "TheIsland_WP" # The map that the server will load
  admin_password: "password2" # Password for admin privileges
  timezone: "America/New_York" # The timezone your server's operating system is set to
  admin_list: # optional list of OSS IDs for server admins, check with `whoami` or `cheat listplayers`
    # - "12345678901234567"
  use_server_api: True # set to True to use the Ark Server API to enable plugins. https://gameservershub.com/forums/resources/ark-survival-ascended-serverapi-crossplay-supported.683/

# Launch options for the server
launch_options:
  # Options prefixed with a question mark
  question_mark:
    # - AllowCrateSpawnsOnTopOfStructures=True # Allows crates to spawn on top of structures
  # Options prefixed with a hyphen
  hyphen:
    - EnableIdlePlayerKick
    - NoBattlEye
    - servergamelog
    - servergamelogincludetribelogs
    - ServerRCONOutputTribeLogs
  # List of mods to include on the server
  mods:
    # - 928988 # Mod ID

# Discord integration settings
discord:
  updates_webhook: "" # Webhook URL for server update messages
  log_webhook: "" # Webhook URL for server log (i.e.; player joined, player died, etc.)
  chat_webhook: "" # Webhook URL for chat messages (i.e.; any global chat messages send will be sent to this webhook)
  events:
    player_connect: True # Sends discord message when a player joins or leaves
    player_died: True # Sends discord message when a player dies
    dino_tamed: True # Sends discord message when a dino is tamed
    global_chat: True # Sends discord message on global chat messages

# Scheduled tasks for server management
tasks:
  restart: # Task for server restart
    enable: True
    description: "Routine server restart"
    interval: 24 # Frequency of restart in hours
    blackout_period: # Time range when restarts are not allowed (e.g. if start is 07:00 and end is 02:00, the event will only take place between 2 am and 7 am)
      start: "07:00"
      end: "02:00"
    warnings: [10, 5, 1] # Warnings before restart at these minute intervals
  # Task for server updates
  update:
    enable: True
    description: "Server update"
    interval: 1 # Frequency of update checks in hours
    warnings: [10, 5, 1] # Warnings before update at these minute intervals
  # Task for destroying wild dinos
  destroy_wild_dinos:
    enable: True
    description: "Routine wild dino wipe"
    interval: 72 # Frequency of wild dino wipe in hours
    blackout_period: # Time range when wild dino wipe is not allowed (e.g. if start is 07:00 and end is 02:00, the event will only take place between 2 am and 7 am)
      start: "07:00"
      end: "02:00"
    warnings: [60, 30, 10, 1] # Warnings before wild dino wipe at these minute intervals
  # Task for server announcements
  announcement:
    enable: True
    interval: 1 # Frequency of announcements in hours
    description: "Thanks for playing, please consider donating to keep the server running!"
  # Task for checking stale server status
  stale:
    enable: True
    interval: 0.5 # Frequency of stale server checks in hours
    threshold: 5 # Consecutive hours a server must be stale before it is restarted
  mod_update:
    enable: True
    description: "Mod update"
    interval: 24 # Frequency of mod update checks in hours
    warnings: [10, 5, 1] # Warnings before restart for mod update at these minute intervals
  server_api_update:
    enable: True
    description: "ARK Server API update"
    interval: 24 # Frequency of server API update checks in hours
    warnings: [10, 5, 1] # Warnings before restart for server API update at these minute intervals

send_welcome_message: True # Sends a welcome message to players on joining the server based on announcement message above

# Configuration ini file overrides for game settings
# config_overrides:
#   Game:
#     /Script/ShooterGame.ShooterGameMode:
#       SupplyCrateLootQualityMultiplier: 1

# program manager settings, should not need adjustment
advanced:
  log_level: info
  sleep_time: 60  # seconds to sleep between server state checks
  server_timeout: 60  # seconds to wait for server to start or stop before exiting
  server_api_timeout: 1800  # seconds to wait for server API to start or stop before exiting
  output_directory: "output"
  log_check_rate: 2  # seconds to wait between log file checks
  mod_update_timestamp_threshold: 60 # number of minutes between installed and latest mod update timestamps before mod is considered needing an update
  download_url:
    steamcmd: "https://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip"
    vc_redist: "https://aka.ms/vs/17/release/vc_redist.x64.exe"
    directx: "https://download.microsoft.com/download/1/7/1/1718CCC4-6315-4D8E-9543-8E28A4E18C4C/dxwebsetup.exe"
    AmazonRootCA1: "https://www.amazontrust.com/repository/AmazonRootCA1.cer"
    r2m02: "http://crt.r2m02.amazontrust.com/r2m02.cer"
