steam_app_id: 2430930

server:
  name: "YourServer"
  ip_address: "192.168.1.42"
  install_path: "C:\\gameservers\\ark_survival_ascended"
  port: 7777
  query_port: 27015
  rcon_port: 32330
  players: 26
  password: ""
  map: "TheIsland_WP"
  admin_password: ""
  timezone: "America/New_York"

launch_options:
  question_mark:
    - AllowCrateSpawnsOnTopOfStructures=True
  hyphen:
    - EnableIdlePlayerKick
    - NoBattlEye
    - servergamelog
    - servergamelogincludetribelogs
    - ServerRCONOutputTribeLogs
    - nosteamclient
    - server
    - log
  mods:
    - 928988


discord:
  updates_webhook: ""
  log_webhook: ""
  chat_webhook: ""
  events:
    player_connect: True
    player_died: True
    dino_tamed: True
    global_chat: True

tasks:
  restart:
    description: "Routine server restart"
    interval: 24 # hours
    blackout_period:
      start: "07:00"
      end: "02:00"
    warnings: [10, 5, 1] # list of minutes to warn user before restart for scheduled restart or update check
  update:
    description: "Server update"
    interval: 1
    warnings: [10, 5, 1]
  destroy_wild_dinos:
    description: "Routine wild dino wipe"
    interval: 72
    blackout_period:
      start: "07:00"
      end: "02:00"
    warnings: [60, 30, 10, 1]
  announcement:
    interval: 1
    description: "Thanks for playing on Brohana. Server is still WIP and adjustments/mods may be made here and there. Discord (also WIP): https://discord.gg/GzbSc9UJ"
  stale:
    interval: 0.5 # interval to check for a stale server in hours
    threshold: 5 # once a server is stale for this many hours, it will be restarted

config_overrides:
  Game:
    /Script/ShooterGame.ShooterGameMode:
      SupplyCrateLootQualityMultiplier: 1.2
      FishingLootQualityMultiplier: 2.8