name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2

    - name: Cache conda
      uses: actions/cache@v2
      with:
        path: |
          ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ hashFiles('**/environment.yml') }}
        restore-keys: |
          ${{ runner.os }}-conda-

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        python-version: "3.11.3"
        environment-file: environment.yml
        activate-environment: ark
        auto-activate-base: false

    - name: Configure conda package dir
      run: conda config --add pkgs_dirs ~/conda_pkgs_dir

    - name: Install Dependencies
      shell: bash -l {0}
      run: |
        conda env update --name ark --file environment.yml

    - name: Install PyInstaller
      shell: bash -l {0}
      run: |
        conda install -c conda-forge pyinstaller || pip install pyinstaller

    - name: Build Executable
      shell: bash -l {0}
      run: |
        cd src
        rm -f __init__.py
        pyinstaller --onefile --name=arkserversuite main.py
        cd ..
        mkdir -p dist
        mv src/dist/arkserversuite.exe dist/arkserversuite.exe

    - name: Zip Executable and Config Directory
      shell: bash -l {0}
      run: |
        7z a release.zip ./dist/arkserversuite.exe ./config/

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: mikepenz/action-gh-release@v0.2.0-a03
        with:
          body: ${{ steps.github_release.outputs.changelog }}
          draft: false
          prerelease: false
          files: ./release.zip
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}