name: Check API Key

on:
  workflow_dispatch:

jobs:
  check-api-key:
    runs-on: ubuntu-latest
    steps:
    - name: Check API Key Length
      run: |
        if [ -z "${{ secrets.CURSEFORGE_API_KEY }}" ]; then
          echo "CURSEFORGE_API_KEY is not set."
        else
          API_KEY="${{ secrets.CURSEFORGE_API_KEY }}"
          echo "Length of CURSEFORGE_API_KEY: ${#API_KEY}"
        fi
